### ISSUE TITLE
[IOS] Paste from Note App not work for version 9.x.x (super_clipboard plugin)

### ISSUE THREAD

**Issue by NhaPCS** [singerdmx/flutter-quill#1627]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.0.5

### Other Flutter Quill packages versions

flutter_quill: ^9.0.5
flutter_quill_extensions: ^9.0.5

### Steps to reproduce

1. Open IOS Note app (that comes with the system)
2. Copy some text from any Note
3. Open Quill Flutter example app => Paste the copied text

### Expected results

It should be paste the text as normal

### Actual results

![e7d3f57e0e54a60aff45](https://github.com/singerdmx/flutter-quill/assets/9054422/767b8fd5-55f7-49b8-b33b-d0ab63ed6fa6)
The result after paste is containing the text styles like this

### Code sample

<details><summary>Code sample</summary>

```dart
return Container(
      decoration: BoxDecoration(
          color: ColorUtils.grey300, borderRadius: DimensionUtil.smallRadius),
      padding: const EdgeInsets.all(12),
      child: QuillEditor(
        focusNode: focusNode ?? FocusNode(),
        scrollController: scrollController,
        configurations: QuillEditorConfigurations(
          contextMenuBuilder: selectionToolbars != null
              ? (context, state) {
                  return TextFieldTapRegion(
                    child: AdaptiveTextSelectionToolbar(
                      anchors: state.contextMenuAnchors,
                      children: selectionToolbars,
                    ),
                  );
                }
              : null,
          scrollable: true,
          autoFocus: false,
          readOnly: readOnly,
          placeholder: placeholder,
          customStyles: DefaultStyles(
            paragraph: DefaultTextBlockStyle(
              TextStyles.textBiggerNarrowStyle
                  .copyWith(fontFamily: TextStyles.fontDefault),
              const VerticalSpacing(0, 0),
              const VerticalSpacing(0, 0),
              null,
            ),
            placeHolder: DefaultListBlockStyle(
                TextStyles.level2BiggerNarrowStyle
                    .copyWith(fontFamily: TextStyles.fontDefault),
                const VerticalSpacing(0, 0),
                const VerticalSpacing(0, 0),
                null,
                null),
          ),
          expands: true,
          padding: EdgeInsets.only(bottom: 50),
          keyboardAppearance: Brightness.light,
          embedBuilders: FlutterQuillEmbeds.editorBuilders(),
          controller: quillController,
        ),
      ),
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Is the issue specific to 9.0.5? because we didn't change anything in `QuillRawEditorState` or copy/paste texts in this update

**Comment by NhaPCS** [comment]
I think the issue is for 9.x.x when you `Replace pasteboard with rich_cliboard`

**Comment by NhaPCS** [comment]
> Is the issue specific to 9.0.5? because we didn't change anything in `QuillRawEditorState` or copy/paste texts in this update


I think the issue is for 9.x.x when you Replace pasteboard with rich_cliboard

**Comment by ellet0** [comment]
> > Is the issue specific to 9.0.5? because we didn't change anything in `QuillRawEditorState` or copy/paste texts in this update
> 
> I think the issue is for 9.x.x when you Replace pasteboard with rich_cliboard

pasteboard is quite outdated so I had no choice + to support html pasting from external websites, can you report the bug on rich_cliboard plugin?

**Comment by ellet0** [comment]
I can try to fix it but I need ask some questions @singerdmx

**Comment by ellet0** [comment]
Are you pasting text using the context menu or something else?

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/e4b3307d-975e-4f85-a4b8-db3eb4741be9)

**Comment by NhaPCS** [comment]
@ellet0 please test it will IOS `Notes` app, I found the issue when I copy text from `Notes` to quill editor version `9.0.5`

**Comment by NhaPCS** [comment]
@ellet0 and one more issue, after pasting a text, it always inserts the `new line` at first. Please refer to below video

https://github.com/singerdmx/flutter-quill/assets/9054422/e35172d6-310f-4677-9c8c-6d45c189e30e

**Comment by ellet0** [comment]
> @ellet0 and one more issue, after pasting a text, it always inserts the `new line` at first. Please refer to below video
> 
>  04b833d620074c9bafa23d0e670f5ca1.mp4

That's known issue and we are woking on it, let's focus on the one from the title.

**Comment by ellet0** [comment]
> @ellet0 please test it will IOS `Notes` app, I found the issue when I copy text from `Notes` to quill editor version `9.0.5`

Yes that's what I did, I'm saying this issue could be happened but it didn't to me, I will try testing on real device

**Comment by NhaPCS** [comment]
plz fix it, thanks! @ellet0

**Comment by ellet0** [comment]
> plz fix it, thanks! @ellet0

I just need a few questions from the old maintainers because they have ore experience with the repo than me, and then I will fix it correctly!

**Comment by ellet0** [comment]
> @ellet0 and one more issue, after pasting a text, it always inserts the `new line` at first. Please refer to below video
> 

This particular bug has been fixed in `9.1.1`

**Comment by ellet0** [comment]
I still can't reproduce the original bug in the title

**Comment by NhaPCS** [comment]
@ellet0 I tested with version `9.1.0`, and that bug is fixed. Thank you so much!

**Comment by ellet0** [comment]
> @ellet0 I tested with version `9.1.0`, and that bug is fixed. Thank you so much!

Hi, which bug exactly has been fixed? Or both?

**Comment by NhaPCS** [comment]
> > @ellet0 I tested with version `9.1.0`, and that bug is fixed. Thank you so much!
> 
> Hi, which bug exactly has been fixed? Or both?

Both, the copy from Notes app bug and auto added `new line` at first also.

**Comment by ellet0** [comment]
> > > @ellet0 I tested with version `9.1.0`, and that bug is fixed. Thank you so much!
> > 
> > Hi, which bug exactly has been fixed? Or both?
> 
> Both, the copy from Notes app bug and auto added `new line` at first also.

Glad to hear that. If you have any questions, feel free to ask at any time!

**Comment by NhaPCS** [comment]
@ellet0 Hi, I think the issues are still there, I just tried again with example of version `9.1.0`. Please check the following video, it includes 2 issues: `new line` at first and copy from Note app

https://github.com/singerdmx/flutter-quill/assets/9054422/a9809903-a18e-449f-863a-d443d65b93e9

**Comment by ellet0** [comment]
> @ellet0 Hi, I think the issues are still there, I just tried again with example of version `9.1.0`. Please check the following video, it includes 2 issues: `new line` at first and copy from Note app
> 
> https://github.com/singerdmx/flutter-quill/assets/9054422/a9809903-a18e-449f-863a-d443d65b93e9
> 
> 

Hi. We haven't published the fix yet. Please try the example and fetch the latest changes

**Comment by NhaPCS** [comment]
@ellet0 I tried the example on master branch

**Comment by ellet0** [comment]
> @ellet0 I tried the example on master branch

The issue of the nrw line should be fixed in the master branch

**Comment by NhaPCS** [comment]
@ellet0 any update?

**Comment by ellet0** [comment]
> @ellet0 any update?

The second issue should be fixed. The first issue still can't reproduce it

**Comment by Mmisiek** [comment]
I still see this issue with 9.2.1 in my app. In the Notes App on iPad, I have a note with increased title font, etc. I "Select All" and "Copy," then I go to Quill Editor, open and Paste from the iOS context menu when I press and hold. In such cases, I see metadata about the fonts used in Notes, and text is copied without formatting. 
<img width="587" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/4585329/2626fe13-529d-40a3-bdcc-acc1a9a49216">

<img width="1276" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/4585329/c29dde6f-cbc9-47aa-b7dc-21bdd8d75097">

**Comment by ellet0** [comment]
I can't debug on real iOS for now, I can reproduce the bug only on simulator which doesn't have Apple notes app

**Comment by Mmisiek** [comment]
> Collaborator

How can I help? I have real devices (phones, iPads, Macs).

**Comment by ellet0** [comment]
> > Collaborator
> 
> How can I help? I have real devices (phones, iPads, Macs).

In your app, add [this plugin](https://pub.dev/packages/super_clipboard)

Setup it only for iOS for now, try to get the clipboard and get the contents as HTML if it can provide it, see how does the HTML looks like and send me the output

**Comment by Mmisiek** [comment]
> > > Collaborator
> > 
> > 
> > How can I help? I have real devices (phones, iPads, Macs).
> 
> In your app, add [this plugin](https://pub.dev/packages/super_clipboard)
> 
> Setup it only for iOS for now, try to get the clipboard and get the contents as HTML if it can provide it, see how does the HTML looks like and send me the output

OK, let me try.

**Comment by ellet0** [comment]
I just found an old iPhone, I will test it but I can't using the example, so I will have to on a real project that have signing setup properly

**Comment by Mmisiek** [comment]
> I just found an old iPhone, I will test it but I can't using the example, so I will have to on a real project that have signing setup properly

I will be able to check this in the evening, if you will not have solution before then I will provide HTML clipboard content.

**Comment by ellet0** [comment]
You can try now 9.2.2 and see if it fix the bug, in my case it did

**Comment by Mmisiek** [comment]
Hi I just tested on iPad and looks ok too. I am not sure if there is no extra lines on top of text but for sure formating is removed. Thank you !

**Comment by Mmisiek** [comment]
I think this can be closed.

**Comment by ellet0** [comment]
> Thank you

You're welcome.
