### ISSUE TITLE
Web: 'RawEditorState' is missing implementations for these members TextSelectionDelegate.copySelection, TextSelectionDelegate.cutSelection,  TextSelectionDelegate.pasteText, TextSelectionDelegate.selectAll

### ISSUE THREAD

**Issue by bobs-bits** [singerdmx/flutter-quill#497]
My issue is about Web

I'm a flutter noob, so, this might be my fault, but I'm getting a build error, which it seems a bunch of other packages have, so I suspect there was an upstream change in flutter-2.5.3/packages/flutter/lib/src/services/text_input.dart.

Below, I have the error message, a link the same issue in another project, and the pointer to the other projects impl of the missing members, in case that is helpful.

I would make a PR, but I have no idea how to test, and you guys might think I knew what I was doing, and the PR might make it to prod. 

**Error Message**

/C:/devtools/flutter-2.5.3/.pub-cache/hosted/pub.dartlang.org/flutter_quill-2.0.14/lib/src/widgets/raw_editor.dart:100:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/devtools/flutter-2.5.3/packages/flutter/lib/src/services/text_input.dart:985:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
/C:/devtools/flutter-2.5.3/packages/flutter/lib/src/services/text_input.dart:965:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
/C:/devtools/flutter-2.5.3/packages/flutter/lib/src/services/text_input.dart:973:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
/C:/devtools/flutter-2.5.3/packages/flutter/lib/src/services/text_input.dart:979:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
Failed to compile application.

**Same Issue in zefyrka project**
https://github.com/glynskyi/zefyrka/issues/31

**zefyrka implementation of members**
https://github.com/glynskyi/zefyrka/blob/main/lib/src/widgets/editor.dart

  @override
  void copySelection(SelectionChangedCause cause) {
    final selection = textEditingValue.selection;
    final plainText = textEditingValue.text;
    if (selection.isCollapsed) {
      return;
    }
    clipboardController.copy(widget.controller, plainText);
    if (cause == SelectionChangedCause.toolbar) {
      bringIntoView(textEditingValue.selection.extent);
      hideToolbar();
    }
  }

  @override
  void cutSelection(SelectionChangedCause cause) {
    final plainText = textEditingValue.text;
    clipboardController.cut(widget.controller, plainText);
    if (cause == SelectionChangedCause.toolbar) {
      bringIntoView(textEditingValue.selection.extent);
      hideToolbar();
    }
  }

  @override
  Future<void> pasteText(SelectionChangedCause cause) async {
    clipboardController.paste(widget.controller, textEditingValue);
    if (cause == SelectionChangedCause.toolbar) {
      bringIntoView(textEditingValue.selection.extent);
      hideToolbar();
    }
  }

  @override
  void selectAll(SelectionChangedCause cause) {
    userUpdateTextEditingValue(
      textEditingValue.copyWith(
        selection: TextSelection(
            baseOffset: 0, extentOffset: textEditingValue.text.length),
      ),
      cause,
    );
    if (cause == SelectionChangedCause.toolbar) {
      bringIntoView(textEditingValue.selection.extent);
    }
  }

**Comment by trevclaridge** [comment]
I'm experiencing the same issue in Flutter 2.5.0-12.0.pre.535.

**Comment by bobs-bits** [comment]
good news!  this appears to be a problem between flutter proper 2.5+ and  flutter_quill-2.0.14-.

I upgraded my dependency to flutter_quill master (as of Dec 5, 2021) and the compilation error is resolved. 

The app I am testing (memo) does not,but I 'm guessing the remaining issue(s?) lie elsewhere.

**Comment by trevclaridge** [comment]
For another flutter noob, how did you upgrade your dependency?

flutter pub upgrade and flutter pub upgrade --major-versions didn't indicate any quill changes (apart from flutter_color_picker).

**Comment by bobs-bits** [comment]
well, that part is a bit ugly.  I replaced the contents of 
<basedir of flutter 2.5.3>/.pub-cache/hosted/pub.dartlang.org/flutter_quill-2.0.14
with the latest source.

I don't know how new versions are published, I don't see tags or branches in the repo.

**Comment by gaganyadav80** [comment]
Correct way to track a flutter packages using git in `pubsepec.yaml` is:
```dart
flutter_quill:
    git: 
      url: https://github.com/singerdmx/flutter-quill.git
      ref: master
```

Tried this but still getting the same error.

Also tried replacing the files in `.pub-cache` but also no luck

**Comment by MagTuxGit** [comment]
https://github.com/singerdmx/flutter-quill/issues/513
